config/routes.rb
Rails.application.routes.draw do

  resources :discounts
  resources :daily_prices
#  get 'pages/home'
  resources :portfolios
  resources :stocks
  resources :tickers
  resources :profits
  #root 'profits#index', as: 'profits_index'
  root :to => 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get "/list_profits", to: 'profits#list_profits'
    get "/list_profits_q1", to: 'profits#list_profits_q1'    
    get "/list_profits_q2", to: 'profits#list_profits_q2'   
    get "/list_profits_q3", to: 'profits#list_profits_q3'            
    get "/list_profits_q4", to: 'profits#list_profits_q4'
    get "/list_sell_alert", to: 'portfolios#list_sell_alert'
    get "/list_buy_alert", to: 'portfolios#list_buy_alert'
    get "/new_low", to: 'portfolios#new_low'
    get "/below_disc", to: 'portfolios#below_disc'    

end

app/models/daily_price.rb
class DailyPrice < ApplicationRecord

  	belongs_to :ticker
    default_scope { order(name: 'asc') }
  	
	before_save :assign_names

	def assign_names
		ticker = Ticker.find(self.ticker_id)
		self.name = ticker.name		

  	end

end

app/controllers/daily_prices_controller.rb
class DailyPricesController < ApplicationController
  before_action :set_daily_price, only: [:show, :edit, :update, :destroy]

  # GET /daily_prices
  # GET /daily_prices.json
  def index
    @daily_prices = DailyPrice.all
  end

  # GET /daily_prices/1
  # GET /daily_prices/1.json
  def show
  end

  # GET /daily_prices/new
  def new
    @daily_price = DailyPrice.new
  end

  # GET /daily_prices/1/edit
  def edit
  end

  # POST /daily_prices
  # POST /daily_prices.json
  def create
    @daily_price = DailyPrice.new(daily_price_params)

    respond_to do |format|
      if @daily_price.save
        format.html { redirect_to @daily_price, notice: 'Daily price was successfully created.' }
        format.json { render :show, status: :created, location: @daily_price }
      else
        format.html { render :new }
        format.json { render json: @daily_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_prices/1
  # PATCH/PUT /daily_prices/1.json
  def update
    respond_to do |format|
      if @daily_price.update(daily_price_params)
        format.html { redirect_to @daily_price, notice: 'Daily price was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_price }
      else
        format.html { render :edit }
        format.json { render json: @daily_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_prices/1
  # DELETE /daily_prices/1.json
  def destroy
    @daily_price.destroy
    respond_to do |format|
      format.html { redirect_to daily_prices_url, notice: 'Daily price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_price
      @daily_price = DailyPrice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_price_params
      params.require(:daily_price).permit(:name, :date, :open_price, :max_price, :min_price, :price, :qty, :ticker_id)
    end
end

app/helpers/daily_prices_helper.rb
module DailyPricesHelper
end

app/views/daily_prices/_form.html.erb
<%= form_with(model: daily_price, local: true) do |form| %>
  <% if daily_price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(daily_price.errors.count, "error") %> prohibited this daily_price from being saved:</h2>

      <ul>
      <% daily_price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker_id %><br />
    <%= form.collection_select :ticker_id, Ticker.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :daily_price_date %>
  </div>

  <div class="field">
    <%= form.label :open_price %>
    <%= form.text_field :open_price, id: :daily_price_open_price %>
  </div>

  <div class="field">
    <%= form.label :max_price %>
    <%= form.text_field :max_price, id: :daily_price_max_price %>
  </div>

  <div class="field">
    <%= form.label :min_price %>
    <%= form.text_field :min_price, id: :daily_price_min_price %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :daily_price_price %>
  </div>

  <div class="field">
    <%= form.label :qty %>
    <%= form.number_field :qty, id: :daily_price_qty %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/daily_prices/edit.html.erb
<h1>Editing Daily Price</h1>

<%= render 'form', daily_price: @daily_price %>

<%= link_to 'Show', @daily_price %> |
<%= link_to 'Back', daily_prices_path %>

app/views/daily_prices/index.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'Daily Prices' %>
<h1>Daily Prices</h1>

<table id="daily_prices" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Open price</th>
      <th>Max price</th>
      <th>Min price</th>
      <th>Price</th>
      <th>Qty</th>
      <th>S</th>      
      <th>E</th>
      <th>D</th>
    </tr>
  </thead>

  <tbody>
    <% @daily_prices.each do |daily_price| %>
      <tr>
        <td><%= daily_price.ticker.name %></td>
        <td><%= daily_price.date %></td>
        <td><%= daily_price.open_price %></td>
        <td><%= daily_price.max_price %></td>
        <td><%= daily_price.min_price %></td>
        <td><%= daily_price.price %></td>
        <td><%= daily_price.qty %></td>
        <td><%= link_to 'Show', daily_price %></td>
        <td><%= link_to 'Edit', edit_daily_price_path(daily_price) %></td>
        <td><%= link_to 'Destroy', daily_price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily Price', new_daily_price_path %>

app/views/daily_prices/new.html.erb
<h1>New Daily Price</h1>

<%= render 'form', daily_price: @daily_price %>

<%= link_to 'Back', daily_prices_path %>

app/views/daily_prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @daily_price.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @daily_price.date %>
</p>

<p>
  <strong>Open price:</strong>
  <%= @daily_price.open_price %>
</p>

<p>
  <strong>Max price:</strong>
  <%= @daily_price.max_price %>
</p>

<p>
  <strong>Min price:</strong>
  <%= @daily_price.min_price %>
</p>

<p>
  <strong>Price:</strong>
  <%= @daily_price.price %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @daily_price.qty %>
</p>

<p>
  <strong>Ticker:</strong>
  <%= @daily_price.ticker_id %>
</p>

<%= link_to 'Edit', edit_daily_price_path(@daily_price) %> |
<%= link_to 'Back', daily_prices_path %>