config/routes.rb
Rails.application.routes.draw do

  resources :discounts
  resources :daily_prices
#  get 'pages/home'
  resources :portfolios
  resources :stocks
  resources :tickers
  resources :profits
  #root 'profits#index', as: 'profits_index'
  root :to => 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get "/list_profits", to: 'profits#list_profits'
    get "/list_profits_q1", to: 'profits#list_profits_q1'    
    get "/list_profits_q2", to: 'profits#list_profits_q2'   
    get "/list_profits_q3", to: 'profits#list_profits_q3'            
    get "/list_profits_q4", to: 'profits#list_profits_q4'
    get "/list_sell_alert", to: 'portfolios#list_sell_alert'
    get "/list_buy_alert", to: 'portfolios#list_buy_alert'
    get "/new_low", to: 'portfolios#new_low'
    get "/below_disc", to: 'portfolios#below_disc'    

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  	belongs_to :ticker
  	enum buy_method: [:min_price, :tenpc_disc, :buy_target]
  	enum sell_method: [:max_price, :consensus, :sell_target]

  	validates :ticker_id, uniqueness: true
#  	validates :buy_unit_cost, :comp_unit_cost, numericality: {greater_than_or_equal_to: 3.0}
#  	validates :buy_qty, :comp_qty, numericality: {greater_than_or_equal_to: 100} 

  	before_save :assign_values

  	private
	def assign_values

		ticker = Ticker.find(self.ticker_id)
		self.name = ticker.name

		self.att_qty = self.buy_qty + self.comp_qty
		self.buy_cost_amt = self.buy_qty * self.buy_unit_cost
		self.comp_cost_amt = self.comp_qty * self.comp_unit_cost		
		self.att_cost_amt = self.buy_cost_amt + self.comp_cost_amt
		self.att_unit_cost = self.att_cost_amt / self.att_qty
      
	end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.order(name: :asc)  
    @discounts = Discount.first 
  end
  
  def new_low
    @portfolios = Portfolio.order(name: :asc)  
    @discounts = Discount.first 
  end

  def below_disc
    @portfolios = Portfolio.order(name: :asc)  
    @discounts = Discount.first 
  end  

  def list_sell_alert
    @portfolios = Portfolio.where("comp_qty > 0").order(name: :asc)
  end

  def list_buy_alert
    @portfolios = Portfolio.where("buy_qty > 0").order(name: :asc)
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:name, :date, :buy_qty, :comp_qty, :att_qty, :buy_unit_cost, :comp_unit_cost, :att_unit_cost, :buy_cost_amt, :comp_cost_amt, :att_cost_amt, :last_sell_price, :sell_qty, :target_sell_price, :buy_method, :sell_method, :ticker_id)
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/below_disc.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'Below Discount' %>
<h1>Portfolios</h1>
<% rate = number_with_precision(@discounts.rate * 100, precision: 0) %>
<h4><%= 'Discount rate = ' + rate.to_s + '%' %></h4>
<% display = 'F' %>

<div class="row">
  <div class="col-sm-1 alignL">
    <b><%= 'Name' %></b>
  </div>
  <div class="col-sm-1 alignC">
    <b><%= 'Date' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Qty' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Cost' %></b>
  </div>  
  <div class="col-sm-2 alignR">
    <b><%= 'Amount' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Price' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Target' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Last' %></b>
  </div> 
  <div class="col-sm-1 alignR">
    <b><%= 'Sell' %></b>
  </div>  
  <div class="col-sm-1 alignR">
    <b><%= 'Buy' %></b>
  </div>   
  <div class="col-sm-1 alignL">
    <b><%= 'Action' %></b>
  </div>  
</div>
    <% @portfolios.each do |portfolio| %>
      <% display = 'F' %>
      
      <% if portfolio.ticker.daily_price.max_price > portfolio.ticker.stock.max_price %>
        <% maxp = portfolio.ticker.daily_price.max_price %>
      <% else %>
        <% maxp = portfolio.ticker.stock.max_price %>
      <% end %>
      <% disc_price = maxp/(1 + @discounts.rate) %>
      <% if (portfolio.ticker.daily_price.price <= disc_price) %> 
        <% if portfolio.buy_qty > 0  %>
          <% display = 'T' %>
        <% end %>
      <% else %>
        <% display = 'F' %>
      <% end %>
      <% if display == 'T' %>
      <div class="row">
        <div class="col-sm-1 list_name"><%= portfolio.name %></div>
        <div class="col-sm-1 alignC"><%= portfolio.date %></div>
        <div class="col-sm-1 alignR">
          <b><%= number_with_delimiter(portfolio.buy_qty) %></b><br/>
          <%= number_with_delimiter(portfolio.comp_qty) %><br/>
          <%= number_with_delimiter(portfolio.att_qty) %>
        </div>
        <div class="col-sm-1 alignR">
          <b><%= number_with_precision(portfolio.buy_unit_cost, precision: 2, delimiter: ",") %></b><br/>
          <%= number_with_precision(portfolio.comp_unit_cost, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.att_unit_cost, precision: 2, delimiter: ",") %>
        </div>
        <div class="col-sm-2 alignR">
          <%= number_with_precision(portfolio.buy_cost_amt, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.comp_cost_amt, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.att_cost_amt, precision: 2, delimiter: ",") %>
        </div>
        <div class="col-sm-1 alignR">
          <% if portfolio.ticker.daily_price.max_price >
            portfolio.ticker.stock.max_price %>
            <% maxp = portfolio.ticker.daily_price.max_price %>
          <% else %>
            <% maxp = portfolio.ticker.stock.max_price %>
          <% end %>

          <%= number_with_precision(maxp, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.ticker.daily_price.price, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.ticker.stock.min_price, precision: 2, delimiter: ",") %>
        </div>   

        <div class="col-sm-1 alignR">
            <% if portfolio.ticker.consensu %>
                <%= number_with_precision(portfolio.ticker.consensu.target_price, precision: 2, delimiter: ",") %><br/>
                <% disc_price = maxp/(1 + @discounts.rate) %>
                <% if disc_price < portfolio.ticker.stock.min_price %>
                  <% disc_price = portfolio.ticker.stock.min_price %>
                <% end %>
                <%= number_with_precision(disc_price, precision: 2, delimiter: ",") %><br/>
                <%= portfolio.ticker.consensu.bhs %>
            <% end %>
        </div>

        <div class="col-sm-1 alignR">
            <%= number_with_precision(portfolio.last_sell_price, precision: 2, delimiter: ",") %><br/>
            <%= 'Sell' %><br/>
            <%= number_with_delimiter(portfolio.sell_qty) %><br/>
        </div>
        <!-- Sell Method & Price -->
        <div class="col-sm-1 alignR">
          <%= portfolio.sell_method.titleize %><br/>
          <% dsp_sell_price = 0.0 %>
          <% case portfolio.sell_method %>
          <% when 'max_price' %>
          <%      dsp_sell_price = portfolio.ticker.stock.max_price %>
          <% when 'consensus' %>
          <%      dsp_sell_price = portfolio.ticker.consensu.target_price %>
          <% when 'sell_target' %>
          <%      dsp_sell_price = portfolio.target_sell_price %>          
          <% end %>
          <%= number_with_precision(dsp_sell_price, precision: 2, delimiter: ",") %><br/>
        </div>
        <!-- Buy Method & Price -->
        <div class="col-sm-1 alignR">
          <%= portfolio.buy_method.titleize %><br/>
          <% dsp_buy_price = 0.0 %>
          <% case portfolio.buy_method %>
          <% when 'min_price' %>
          <%      dsp_buy_price = portfolio.ticker.stock.min_price %>
          <% when 'tenpc_disc' %>
          <%      dsp_buy_price = portfolio.ticker.stock.max_price/1.1 %>
          <% when 'buy_target' %>
          <%      dsp_buy_price = portfolio.buy_unit_cost %>          
          <% end %>
          <%= number_with_precision(dsp_buy_price, precision: 2, delimiter: ",") %><br/>
        </div>

        <div class="col-sm-1 list_actions">
          <%= link_to 'Show', portfolio %><br/>
          <%= link_to 'Edit', edit_portfolio_path(portfolio) %><br/>
          <%= link_to 'Delete', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
      <br/>
      <% end %>
    <% end %>


<br>

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'Portfolios' %>
<h1>Portfolios</h1>
<% rate = number_with_precision(@discounts.rate * 100, precision: 0) %>
<h4><%= 'Discount rate = ' + rate.to_s + '%' %></h4>
<div class="row">
  <div class="col-sm-1 alignL">
    <b><%= 'Name' %></b>
  </div>
  <div class="col-sm-1 alignC">
    <b><%= 'Date' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Qty' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Cost' %></b>
  </div>  
  <div class="col-sm-2 alignR">
    <b><%= 'Amount' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Price' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Target' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Last' %></b>
  </div> 
  <div class="col-sm-1 alignR">
    <b><%= 'Sell' %></b>
  </div>  
  <div class="col-sm-1 alignR">
    <b><%= 'Buy' %></b>
  </div>   
  <div class="col-sm-1 alignL">
    <b><%= 'Action' %></b>
  </div>  
</div>
    <% @portfolios.each do |portfolio| %>
      <div class="row">
        <div class="col-sm-1 list_name"><%= portfolio.name %></div>
        <div class="col-sm-1 alignC"><%= portfolio.date %></div>
        <div class="col-sm-1 alignR">
          <b><%= number_with_delimiter(portfolio.buy_qty) %></b><br/>
          <%= number_with_delimiter(portfolio.comp_qty) %><br/>
          <%= number_with_delimiter(portfolio.att_qty) %>
        </div>
        <div class="col-sm-1 alignR">
          <b><%= number_with_precision(portfolio.buy_unit_cost, precision: 2, delimiter: ",") %></b><br/>
          <%= number_with_precision(portfolio.comp_unit_cost, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.att_unit_cost, precision: 2, delimiter: ",") %>
        </div>
        <div class="col-sm-2 alignR">
          <%= number_with_precision(portfolio.buy_cost_amt, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.comp_cost_amt, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.att_cost_amt, precision: 2, delimiter: ",") %>
        </div>
        <div class="col-sm-1 alignR">
          <% if portfolio.ticker.daily_price.max_price >
            portfolio.ticker.stock.max_price %>
            <% maxp = portfolio.ticker.daily_price.max_price %>
          <% else %>
            <% maxp = portfolio.ticker.stock.max_price %>
          <% end %>

          <%= number_with_precision(maxp, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.ticker.daily_price.price, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.ticker.stock.min_price, precision: 2, delimiter: ",") %>
        </div>   

        <div class="col-sm-1 alignR">
            <% if portfolio.ticker.consensu %>
                <%= number_with_precision(portfolio.ticker.consensu.target_price, precision: 2, delimiter: ",") %><br/>
                <% disc_price = maxp/(1 + @discounts.rate) %>
                <% if disc_price < portfolio.ticker.stock.min_price %>
                  <% disc_price = portfolio.ticker.stock.min_price %>
                <% end %>
                <%= number_with_precision(disc_price, precision: 2, delimiter: ",") %><br/>
                <%= portfolio.ticker.consensu.bhs %>
            <% end %>
        </div>

        <div class="col-sm-1 alignR">
            <%= number_with_precision(portfolio.last_sell_price, precision: 2, delimiter: ",") %><br/>
            <%= 'Sell' %><br/>
            <%= number_with_delimiter(portfolio.sell_qty) %><br/>
        </div>
        <!-- Sell Method & Price -->
        <div class="col-sm-1 alignR">
          <%= portfolio.sell_method.titleize %><br/>
          <% dsp_sell_price = 0.0 %>
          <% case portfolio.sell_method %>
          <% when 'max_price' %>
          <%      dsp_sell_price = portfolio.ticker.stock.max_price %>
          <% when 'consensus' %>
          <%      dsp_sell_price = portfolio.ticker.consensu.target_price %>
          <% when 'sell_target' %>
          <%      dsp_sell_price = portfolio.target_sell_price %>          
          <% end %>
          <%= number_with_precision(dsp_sell_price, precision: 2, delimiter: ",") %><br/>
        </div>
        <!-- Buy Method & Price -->
        <div class="col-sm-1 alignR">
          <%= portfolio.buy_method.titleize %><br/>
          <% dsp_buy_price = 0.0 %>
          <% case portfolio.buy_method %>
          <% when 'min_price' %>
          <%      dsp_buy_price = portfolio.ticker.stock.min_price %>
          <% when 'tenpc_disc' %>
          <%      dsp_buy_price = portfolio.ticker.stock.max_price/1.1 %>
          <% when 'buy_target' %>
          <%      dsp_buy_price = portfolio.buy_unit_cost %>          
          <% end %>
          <%= number_with_precision(dsp_buy_price, precision: 2, delimiter: ",") %><br/>
        </div>

        <div class="col-sm-1 list_actions">
          <%= link_to 'Show', portfolio %><br/>
          <%= link_to 'Edit', edit_portfolio_path(portfolio) %><br/>
          <%= link_to 'Delete', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
      <br/>
    <% end %>


<br>

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/portfolios/list_buy_alert.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'Buy' %>
<div class ="page-header text-left" > 
  <h1><%= "Buy Alert" %></h1>
</div>

<table  id="buy_alert" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Qty</th>
      <th>Target</th>  
      <th>Price</th>
      <th>Diff</th> 
      <th>Spd</th>             
      <th>Cost</th>            
      <th>Min</th> 
      <th>IAA</th>   
      <th>Method</th>        
    </tr>
  </thead>
  <tbody>
    <% @portfolios.each do |portfolio| %>
      <% spreads = num_of_spread(portfolio.ticker.daily_price.price,portfolio.buy_unit_cost).to_i %>
      <tr>
        <td><%= portfolio.name %></td>
        <td><%= number_with_delimiter(portfolio.buy_qty, delimiter: ",") %></td>
        <td><%= number_with_precision(portfolio.buy_unit_cost, precision: 2) %></td>
        <td><%= number_with_precision(portfolio.ticker.daily_price.price, precision: 2) %></td>
        <% diff = portfolio.buy_unit_cost - portfolio.ticker.daily_price.price %>
        <td><%= number_with_precision(diff, precision: 2) %></td>  
        <td><%= spreads %></td>              
        <td><%= number_with_precision(portfolio.comp_unit_cost, precision: 2) %></td>
        <td><%= number_with_precision(portfolio.ticker.stock.min_price, precision: 2) %></td>
        <% if portfolio.ticker.consensu %>
        <td><%= number_with_precision(portfolio.ticker.consensu.target_price, precision: 2) %></td>
        <% else %>
        <td><%= 0.00 %></td>  
        <% end %>
        <td><%= portfolio.buy_method.titleize %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/new_low.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'Portfolios' %>
<h1>Portfolios</h1>
<% rate = number_with_precision(@discounts.rate * 100, precision: 0) %>
<h4><%= 'Discount rate = ' + rate.to_s + '%' %></h4>
<% display = 'F' %>

<div class="row">
  <div class="col-sm-1 alignL">
    <b><%= 'Name' %></b>
  </div>
  <div class="col-sm-1 alignC">
    <b><%= 'Date' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Qty' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Cost' %></b>
  </div>  
  <div class="col-sm-2 alignR">
    <b><%= 'Amount' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Price' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Target' %></b>
  </div>
  <div class="col-sm-1 alignR">
    <b><%= 'Last' %></b>
  </div> 
  <div class="col-sm-1 alignR">
    <b><%= 'Sell' %></b>
  </div>  
  <div class="col-sm-1 alignR">
    <b><%= 'Buy' %></b>
  </div>   
  <div class="col-sm-1 alignL">
    <b><%= 'Action' %></b>
  </div>  
</div>
    <% @portfolios.each do |portfolio| %>
      <% display = 'F' %>
      <% if portfolio.ticker.daily_price.price <= portfolio.ticker.stock.min_price %>
      <% display = 'T' %>
      <% else %>
      <% display = 'F' %>
      <% end %>
      <% if display == 'T' %>
      <div class="row">
        <div class="col-sm-1 list_name"><%= portfolio.name %></div>
        <div class="col-sm-1 alignC"><%= portfolio.date %></div>
        <div class="col-sm-1 alignR">
          <b><%= number_with_delimiter(portfolio.buy_qty) %></b><br/>
          <%= number_with_delimiter(portfolio.comp_qty) %><br/>
          <%= number_with_delimiter(portfolio.att_qty) %>
        </div>
        <div class="col-sm-1 alignR">
          <b><%= number_with_precision(portfolio.buy_unit_cost, precision: 2, delimiter: ",") %></b><br/>
          <%= number_with_precision(portfolio.comp_unit_cost, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.att_unit_cost, precision: 2, delimiter: ",") %>
        </div>
        <div class="col-sm-2 alignR">
          <%= number_with_precision(portfolio.buy_cost_amt, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.comp_cost_amt, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.att_cost_amt, precision: 2, delimiter: ",") %>
        </div>
        <div class="col-sm-1 alignR">
          <% if portfolio.ticker.daily_price.max_price >
            portfolio.ticker.stock.max_price %>
            <% maxp = portfolio.ticker.daily_price.max_price %>
          <% else %>
            <% maxp = portfolio.ticker.stock.max_price %>
          <% end %>

          <%= number_with_precision(maxp, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.ticker.daily_price.price, precision: 2, delimiter: ",") %><br/>
          <%= number_with_precision(portfolio.ticker.stock.min_price, precision: 2, delimiter: ",") %>
        </div>   

        <div class="col-sm-1 alignR">
            <% if portfolio.ticker.consensu %>
                <%= number_with_precision(portfolio.ticker.consensu.target_price, precision: 2, delimiter: ",") %><br/>
                <% disc_price = maxp/(1 + @discounts.rate) %>
                <% if disc_price < portfolio.ticker.stock.min_price %>
                  <% disc_price = portfolio.ticker.stock.min_price %>
                <% end %>
                <%= number_with_precision(disc_price, precision: 2, delimiter: ",") %><br/>
                <%= portfolio.ticker.consensu.bhs %>
            <% end %>
        </div>

        <div class="col-sm-1 alignR">
            <%= number_with_precision(portfolio.last_sell_price, precision: 2, delimiter: ",") %><br/>
            <%= 'Sell' %><br/>
            <%= number_with_delimiter(portfolio.sell_qty) %><br/>
        </div>
        <!-- Sell Method & Price -->
        <div class="col-sm-1 alignR">
          <%= portfolio.sell_method.titleize %><br/>
          <% dsp_sell_price = 0.0 %>
          <% case portfolio.sell_method %>
          <% when 'max_price' %>
          <%      dsp_sell_price = portfolio.ticker.stock.max_price %>
          <% when 'consensus' %>
          <%      dsp_sell_price = portfolio.ticker.consensu.target_price %>
          <% when 'sell_target' %>
          <%      dsp_sell_price = portfolio.target_sell_price %>          
          <% end %>
          <%= number_with_precision(dsp_sell_price, precision: 2, delimiter: ",") %><br/>
        </div>
        <!-- Buy Method & Price -->
        <div class="col-sm-1 alignR">
          <%= portfolio.buy_method.titleize %><br/>
          <% dsp_buy_price = 0.0 %>
          <% case portfolio.buy_method %>
          <% when 'min_price' %>
          <%      dsp_buy_price = portfolio.ticker.stock.min_price %>
          <% when 'tenpc_disc' %>
          <%      dsp_buy_price = portfolio.ticker.stock.max_price/1.1 %>
          <% when 'buy_target' %>
          <%      dsp_buy_price = portfolio.buy_unit_cost %>          
          <% end %>
          <%= number_with_precision(dsp_buy_price, precision: 2, delimiter: ",") %><br/>
        </div>

        <div class="col-sm-1 list_actions">
          <%= link_to 'Show', portfolio %><br/>
          <%= link_to 'Edit', edit_portfolio_path(portfolio) %><br/>
          <%= link_to 'Delete', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
      <br/>
      <% end %>
    <% end %>


<br>

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @portfolio.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @portfolio.date %>
</p>

<p>
  <strong>Buy qty:</strong>
  <%= @portfolio.buy_qty %>
</p>

<p>
  <strong>Comp qty:</strong>
  <%= @portfolio.comp_qty %>
</p>

<p>
  <strong>Att qty:</strong>
  <%= @portfolio.att_qty %>
</p>

<p>
  <strong>Buy unit cost:</strong>
  <%= @portfolio.buy_unit_cost %>
</p>

<p>
  <strong>Comp unit cost:</strong>
  <%= @portfolio.comp_unit_cost %>
</p>

<p>
  <strong>Att unit cost:</strong>
  <%= @portfolio.att_unit_cost %>
</p>

<p>
  <strong>Buy cost amt:</strong>
  <%= @portfolio.buy_cost_amt %>
</p>

<p>
  <strong>Comp cost amt:</strong>
  <%= @portfolio.comp_cost_amt %>
</p>

<p>
  <strong>Att cost amt:</strong>
  <%= @portfolio.att_cost_amt %>
</p>

<p>
  <strong>Last sell price:</strong>
  <%= @portfolio.last_sell_price %>
</p>

<p>
  <strong>Sell qty:</strong>
  <%= @portfolio.sell_qty %>
</p>

<p>
  <strong>Target sell price:</strong>
  <%= @portfolio.target_sell_price %>
</p>

<p>
  <strong>Buy method:</strong>
  <%= @portfolio.buy_method.titleize %>
</p>

<p>
  <strong>Sell method:</strong>
  <%= @portfolio.sell_method.titleize %>
</p>

<p>
  <strong>Ticker:</strong>
  <%= @portfolio.ticker.name %>
</p>

<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>