config/routes.rb
Rails.application.routes.draw do

  resources :discounts
  resources :daily_prices
#  get 'pages/home'
  resources :portfolios
  resources :stocks
  resources :tickers
  resources :profits
  #root 'profits#index', as: 'profits_index'
  root :to => 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get "/list_profits", to: 'profits#list_profits'
    get "/list_profits_q1", to: 'profits#list_profits_q1'    
    get "/list_profits_q2", to: 'profits#list_profits_q2'   
    get "/list_profits_q3", to: 'profits#list_profits_q3'            
    get "/list_profits_q4", to: 'profits#list_profits_q4'
    get "/list_sell_alert", to: 'portfolios#list_sell_alert'
    get "/list_buy_alert", to: 'portfolios#list_buy_alert'
    get "/new_low", to: 'portfolios#new_low'
    get "/below_disc", to: 'portfolios#below_disc'    

end

app/models/discount.rb
class Discount < ApplicationRecord
end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController
  before_action :set_discount, only: [:show, :edit, :update, :destroy]

  # GET /discounts
  # GET /discounts.json
  def index
    @discounts = Discount.all
  end

  # GET /discounts/1
  # GET /discounts/1.json
  def show
  end

  # GET /discounts/new
  def new
    @discount = Discount.new
  end

  # GET /discounts/1/edit
  def edit
  end

  # POST /discounts
  # POST /discounts.json
  def create
    @discount = Discount.new(discount_params)

    respond_to do |format|
      if @discount.save
        format.html { redirect_to @discount, notice: 'Discount was successfully created.' }
        format.json { render :show, status: :created, location: @discount }
      else
        format.html { render :new }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discounts/1
  # PATCH/PUT /discounts/1.json
  def update
    respond_to do |format|
      if @discount.update(discount_params)
        format.html { redirect_to @discount, notice: 'Discount was successfully updated.' }
        format.json { render :show, status: :ok, location: @discount }
      else
        format.html { render :edit }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discounts/1
  # DELETE /discounts/1.json
  def destroy
    @discount.destroy
    respond_to do |format|
      format.html { redirect_to discounts_url, notice: 'Discount was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discount
      @discount = Discount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discount_params
      params.require(:discount).permit(:rate)
    end
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/views/discounts/_form.html.erb
<% content_for :title, 'Discounts' %>
<%= form_with(model: discount, local: true) do |form| %>
  <% if discount.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discount.errors.count, "error") %> prohibited this discount from being saved:</h2>

      <ul>
      <% discount.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rate %>
    <%= form.text_field :rate, id: :discount_rate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/discounts/edit.html.erb
<h1>Editing Discount</h1>

<%= render 'form', discount: @discount %>

<%= link_to 'Show', @discount %> |
<%= link_to 'Back', discounts_path %>

app/views/discounts/index.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'Discounts' %>
<h1>Discounts</h1>

<table>
  <thead>
    <tr>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discounts.each do |discount| %>
      <tr>
        <td><%= discount.rate %></td>
        <td><%= link_to 'Show', discount %></td>
        <td><%= link_to 'Edit', edit_discount_path(discount) %></td>
        <td><%= link_to 'Destroy', discount, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discount', new_discount_path %>

app/views/discounts/new.html.erb
<h1>New Discount</h1>

<%= render 'form', discount: @discount %>

<%= link_to 'Back', discounts_path %>

app/views/discounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rate:</strong>
  <%= @discount.rate %>
</p>

<%= link_to 'Edit', edit_discount_path(@discount) %> |
<%= link_to 'Back', discounts_path %>