config/routes.rb
Rails.application.routes.draw do

  resources :discounts
  resources :daily_prices
#  get 'pages/home'
  resources :portfolios
  resources :stocks
  resources :tickers
  resources :profits
  #root 'profits#index', as: 'profits_index'
  root :to => 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get "/list_profits", to: 'profits#list_profits'
    get "/list_profits_q1", to: 'profits#list_profits_q1'    
    get "/list_profits_q2", to: 'profits#list_profits_q2'   
    get "/list_profits_q3", to: 'profits#list_profits_q3'            
    get "/list_profits_q4", to: 'profits#list_profits_q4'
    get "/list_sell_alert", to: 'portfolios#list_sell_alert'
    get "/list_buy_alert", to: 'portfolios#list_buy_alert'
    get "/new_low", to: 'portfolios#new_low'
    get "/below_disc", to: 'portfolios#below_disc'    

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

    <head>
        <title>
            <% if content_for?(:title) %>
                <%= yield :title %>
            <% else %>
                PortMy
            <% end %>
        </title>
    	<%= csrf_meta_tags %>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    </head>

    <body class="<%= controller.controller_name %>">
  	    <div id="banner">
  		    <%= image_tag 'logo_en.jpg', alt: 'SetTrade' %>
  		    <span class="title">
                <%= @page_title || "Profits" %>
            </span>
  	    </div>
  	    <div id="columns">
  		    <div id="side">
                <ul>
                    <li><%= link_to 'Home', root_path %></li>

                    <li><%= link_to 'Profits Grid', "/list_profits" %></li>
                    <li><%= link_to 'Discount', discounts_path %></li>
                    
                    <li><%= link_to 'Portfolios', portfolios_path %></li>
                    <li><%= link_to 'Below Disc', "below_disc" %></li>
                    <li><%= link_to 'New Low', "new_low" %></li>
                    <li><%= link_to 'Buy Alert', "/list_buy_alert" %></li>
                    <li><%= link_to 'Sell Alert', "/list_sell_alert" %></li>

                    <li><%= link_to 'Profits-Q1', "/list_profits_q1" %></li>
                    <li><%= link_to 'Profits-Q2', "/list_profits_q2" %></li>
                    <li><%= link_to 'Profits-Q3', "/list_profits_q3" %></li>
                    <li><%= link_to 'Profits-Q4', "/list_profits_q4" %></li>
                    <li><%= link_to 'Daily Price', daily_prices_path %></li>

                    <li><%= link_to 'Tickers', tickers_path %></li>
                    <li><%= link_to 'Stocks', stocks_path %></li>
                    <li><%= link_to 'Profits', profits_path %></li>
                </ul>
  		    </div> <!-- end of side -->
  		    <div class="container-fluid" id="main">
    		  <%= yield %>
    	   </div> <!-- end of containter -->
        </div>	<!-- end of columns -->
    </body>
</html>